import React, { useEffect, useState } from 'react'
import { BsArrowRight, BsWhatsapp } from 'react-icons/bs'
import { TiSocialTwitter } from 'react-icons/ti'
import {
  WhatsappShareButton,
  TwitterShareButton
} from 'next-share';
import Link from 'next/link';
import data from '../data/bioData.json'
import { useRouter } from 'next/router';
import Head from 'next/head';
import Card from '@/components/Card';

const fullBio = () => {

  const [bioData, setBioData] = useState()
  const [briefBioContent, setBriefBioContent] = useState()
  const [shareUrl, setShareUrl] = useState("")
  const router = useRouter();
  const id = router.query.id
  const [randomIndexArray, setRandomIndexArray] = useState()

  useEffect(() => {
    if (id) {
      let tempData = data.filter((item) => item.id === parseInt(id))
      setBioData(tempData[0])
      setBriefBioContent(tempData[0]?.briefBio.split("\n\n"))
      setShareUrl(window.location.href)
      if (!randomIndex().includes(parseInt(id))) {
        setRandomIndexArray(randomIndex())
      }
    }
  }, [id])

  console.log("randomIndexArray", randomIndexArray)

  const randomIndex = () => {
    let randomIndex1 = Math.floor(Math.random() * (data.length + 1))
    let randomIndex2 = Math.floor(Math.random() * (data.length + 1))
    if (randomIndex1 === randomIndex2) {
      randomIndex()
    }
    return [randomIndex1, randomIndex2]
  }

  return (
    <>
      <Head>
        <title>BIO - {bioData?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='mx-3 px-3 md:mx-10 md:px-2 my-4'>
        <div className="sm:flex items-center sm:px-7 justify-between w-full border-b-2 border-gray-100 py-4 sticky top-14 sm:top-[88px] z-30 bg-white">

          <div className='flex items-center'>
            <img alt="pic" src={bioData?.image} className="w-28 h-28 sm:w-36 sm:h-36 rounded-full flex-shrink-0 object-cover object-center" />
            <span className="flex-grow flex flex-col ml-4 sm:ml-10">
              <span className="text-right sm:text-left title-font font-medium mr-0 ml-auto sm:ml-0 text-gray-900 tracking-widest uppercase text-sm sm:text-base">{bioData?.name}</span>
              <span className="text-right sm:text-left mr-0 ml-auto sm:ml-0 w-fit text-xs font-medium tracking-widest uppercase">{bioData?.profession}</span>
              <span className="text-right sm:text-left text-gray-400 text-xs tracking-widest mt-0.5 mr-0 ml-auto sm:ml-0">({bioData?.origin})</span>
            </span>
          </div>

          <div className='sm:flex'>
            {/* Share */}
            <div className="flex items-center w-full justify-end">
              <WhatsappShareButton
                url={shareUrl} >
                <BsWhatsapp className='text-2xl text-green-500 mr-4 hover:scale-125 ease-in-out duration-200' />
              </WhatsappShareButton>
              <TwitterShareButton
                url={shareUrl} >
                <TiSocialTwitter className='text-4xl text-rose-400 mr-4 hover:scale-125 ease-in-out duration-200' />
              </TwitterShareButton>
            </div>
          </div>
        </div>

        <div className='mb-8 sm:px-7 mt-3 sm:mt-6'>
          {briefBioContent?.map((item, index) => {
            return (
              <p className="leading-relaxed mb-2" key={index}>
                {item}
              </p>
            )
          })}
        </div>

        <div className="cursor-pointer w-fit mx-auto my-6 md:my-12">
          <Link href={"/"}>
            <div className='text-rose-400 flex items-center space-x-1 hover:scale-110 duration-300 hover:underline hover:underline-offset-8'>
              <span className='font-semibold'>
                Other Famous Personalities
              </span>
              <BsArrowRight className='text-xl' />
            </div>
          </Link>
        </div>
      </div>

      <div className='mt-3 md:mt-6 mx-6 lg:mx-16'>
        <h2 className="custom-font uppercase text-2xl md:text-4xl font-semibold bg-gradient-to-t from-rose-500 to-pink-400 text-transparent bg-clip-text">Some Other Famous Personalities</h2>

        <div className='my-4 flex flex-wrap'>
          {randomIndexArray && data.map((item, index) => {
            if (item?.id === randomIndexArray[0] || item?.id === randomIndexArray[1]) {
              return <Card key={index} data={item} />
            }
          })}
        </div>
        <div className="cursor-pointer w-fit mx-auto my-3 md:my-6">
          <Link href={"/"}>
            <div className='text-rose-400 flex items-center space-x-1 hover:scale-110 duration-300 hover:underline hover:underline-offset-8'>
              <span className='font-semibold'>
                View More
              </span>
              <BsArrowRight className='text-xl' />
            </div>
          </Link>
        </div>
      </div>
    </>
  )
}

export default fullBio